---
exclude_paths:
  - .ansible/
  - .github/
  - venv/
  # ansible-lint fails to lint this file because it uses an rhel role
  - roles/network/tasks/main.yml
skip_list:
  # we would love to clean these up at some point,
  # but we also want to include the collection in
  # the prefix and are waiting for that to be supported.
  - var-naming[no-role-prefix]
  # not currently planned, but would be nice
  - galaxy[no-changelog]
  # we still need EL8 support, so we allow ansible 2.14
  - meta-runtime[unsupported-version]
  # ignore line length
  - yaml[line-length]
