---
namespace: radiorabe
name: rabe_foreman
version: 0.0.0
readme: README.md
authors:
  - Lucas Bickel <@hairmare>
description: GitOps our Foreman
license_file: LICENSE
tags:
  - radiorabe
  - foreman
  - infrastructure
dependencies:
  ansible.posix: ">=1.3.0"
  community.general: ">=3.7.0"
  community.postgresql: ">=3.3.0" # for zabbix
  community.zabbix: ">=1.9.0"
  radiorabe.common: ">=0.2.0"
  radiorabe.foreman: ">=0.9.0"
  radiorabe.podman: ">=0.1.0"
  radiorabe.rabe_zabbix: ">=0.1.1"
  theforeman.foreman: ">=3.5.0"
  freeipa.ansible_freeipa: ">=1.11.0"
repository: https://github.com/radiorabe/ansible-collection-rabe_foreman
documentation: https://github.com/radiorabe/ansible-collection-rabe_foreman/blob/main/README.md
homepage: hhttps://github.com/radiorabe/ansible-collection-rabe_foreman
issues: https://github.com/radiorabe/ansible-collection-rabe_foreman/issues
