---
foreman_hostgroup:
  name: RaBe Base
  description: RaBe Core configures the bare minimum of non OS specific things.
  parent: RaBe Core
  organization: RaBe
  location: Sulgenrain
  architecture: x86_64
  ansible_roles:
    - radiorabe.common.base
    - redhat.rhel_system_roles.firewall
    - redhat.rhel_system_roles.cockpit
    - redhat.rhel_system_roles.selinux
    - radiorabe.common.rabe_backup
  parameters:
    - name: cockpit_certificates
      parameter_type: yaml
      value:
        - name: monger-cockpit
          dns:
            - "{{ '{{ ansible_host }}' }}"
          principal: "HTTP/{{ '{{ ansible_host }}' }}@INT.RABE.CH"
          ca: ipa
          key_size: 4096
    - name: cockpit_packages
      parameter_type: yaml
      value:
        - cockpit
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-podman
    - name: foreman_scap_client_server
      parameter_type: string
      value: foreman.service.int.rabe.ch
    - name: only_subscription_manager_repos
      parameter_type: boolean
      value: true
    - name: package_upgrade
      parameter_type: boolean
      value: false
    # base options for [radiorabe.rabe_zabbix.agent](https://github.com/radiorabe/ansible-collection-rabe_zabbix/tree/main/roles/agent)
    # TODO: remove override once we are fully migrated to agent2 and we can use the default from the role
    - name: radiorabe_zabbix_agent_server
      parameter_type: string
      value: vm-0040.service.int.rabe.ch
    - name: radiorabe_zabbix_agent_serveractive
      parameter_type: string
      value: vm-0040.service.int.rabe.ch
    - name: selinux_policy
      parameter_type: string
      value: targeted
    - name: selinux_state
      parameter_type: string
      value: enforcing
    - name: subscription_manager
      parameter_type: boolean
      value: true
    # base options for [timesync](https://github.com/linux-system-roles/timesync) role
    - name: timesync_ntp_servers
      parameter_type: yaml
      value:
        - hostname: ntp-01.service.int.rabe.ch
          iburst: true
        - hostname: ntp-02.service.int.rabe.ch
          iburst: true
        - hostname: ntp-03.service.int.rabe.ch
          iburst: true
        - hostname: ntp-04.service.int.rabe.ch
          iburst: true
        - hostname: ntp-05.service.int.rabe.ch
          iburst: true
    - name: time-zone
      parameter_type: string
      value: "Europe/Zurich"
