---
foreman_hostgroup:
  name: CentOS 7
  description: CentOS 7 configures the RaBe CentOS 7 baseline and serves as a catch-all for imported CentOS 7 infrastructure.
  parent: RaBe Core/RaBe Base/EL7
  organization: RaBe
  locations:
    - Sulgenrain
  operatingsystem: CentOS 7
