---
foreman_hostgroup:
  name: AlmaLinux 9 VMs
  description: AlmaLinux 9 general purpose virtual machines.
  parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
  organization: RaBe
  location: Sulgenrain
  compute_resource: ovirt
