---
foreman_hostgroup:
  name: vm-0041.service.int.rabe.ch
  description: AlmaLinux 9 VM for Letsencrypt certificate renewal on reverse proxies
  parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9/AlmaLinux 9 VMs
  organization: RaBe
  locations: Sulgenrain
  ansible_roles:
    - radiorabe.common.selinux_modules
    - redhat.rhel_system_roles.certificate
    - radiorabe.common.local_user
    - redhat.rhel_system_roles.kernel_settings
    - radiorabe.common.files
    - redhat.rhel_system_roles.podman
  parameters:
    - name: certificate_requests
      parameter_type: yaml
      value:
        - name: kanboard
          dns:
            - kanboard-new.service.int.rabe.ch
          ca: ipa
          principal: HTTP/kanboard-new.service.int.rabe.ch@INT.RABE.CH
          key_size: 4096
          run_after: "/usr/bin/cp /etc/pki/tls/*/kanboard.* /home/kanboard/ssl/ \n/usr/bin/chown
            kanboard: /home/kanboard/ssl/*\ncd /home/kanboard\n/usr/bin/sudo -u kanboard /usr/bin/podman
            pod restart kanboard\n"
    - name: kanboard_db_password
      parameter_type: string
      hidden_value: true
      value: "{{ undef('variable kanboard_db_password needs to be set in host') }}"
    - name: kanboard_db_user
      parameter_type: string
      value: "{{ undef('variable kanboard_db_user needs to be set in host') }}"
    - name: kanboard_ldap_password
      parameter_type: string
      hidden_value: true
      value: "{{ undef('variable kanboard_ldap_password needs to be set in host') }}"
    - name: kanboard_ldap_server
      parameter_type: string
      value: "{{ undef('variable kanboard_ldap_server needs to be set in host') }}"
    - name: kanboard_ldap_username
      parameter_type: string
      value: "{{ undef('variable kanboard_ldap_username needs to be set in host') }}"
    - name: kanboard_smtp_hostname
      parameter_type: string
      value: "{{ undef('variable kanboard_smtp_hostname needs to be set in host') }}"
    - name: kanboard_smtp_password
      parameter_type: string
      hidden_value: true
      value: "{{ undef('variable kanboard_smtp_password needs to be set in host') }}"
    - name: kanboard_smtp_username
      parameter_type: string
      value: "{{ undef('variable kanboard_smtp_username needs to be set in host') }}"
    - name: kanboard_reverse_proxy_default_admin
      parameter_type: string
      value: "{{ undef('variable kanboard_reverse_proxy_default_admin needs to be set in host') }}"
    - name: kernel_settings_sysctl
      parameter_type: yaml
      value:
        - name: net.ipv4.ip_unprivileged_port_start
          value: 80
    - name: local_user_username
      parameter_type: string
      value: kanboard
    - name: podman_containers_conf
      parameter_type: yaml
      value:
        containers:
          log_driver: k8s-file
          log_size_max: 1073741824
    - name: podman_create_host_directories
      parameter_type: boolean
      value: true
    - name: podman_firewall
      parameter_type: yaml
      value:
        - service:
            - http
            - https
          state: enabled
    - name: podman_kube_specs
      parameter_type: yaml
      value:
        - state: started
          kube_file_content:
            apiVersion: v1
            kind: Pod
            metadata:
              name: kanboard
            spec:
              containers:
                - name: kanboard
                  restart: always
                  image: quay.io/kanboard/kanboard:v1.2.51
                  ports:
                    - containerPort: 80
                      hostPort: 80
                    - containerPort: 443
                      hostPort: 443
                  volumeMounts:
                    - mountPath: "/var/www/app/data:Z"
                      name: kanboard_data
                    - mountPath: "/var/www/app/plugins:Z"
                      name: kanboard_plugins
                    - mountPath: "/etc/nginx/ssl:ro,Z"
                      name: kanboard_ssl
                    - mountPath: "/etc/ssl/certs/ca-certificates.crt:ro"
                      name: ca_certs
                    - mountPath: "/etc/php84/conf.d/z.ini:ro,Z"
                      name: php_fpm_ini
                  env:
                    - name: DEBUG
                      value: false
                    - name: LOG_DRIVER
                      value: system
                    - name: DB_DRIVER
                      value: postgres
                    - name: DB_USERNAME
                      value: "{{ kanboard_db_user }}"
                    - name: DB_PASSWORD
                      value: "{{ kanboard_db_password }}"
                    - name: DB_HOSTNAME
                      value: postgresql.service.int.rabe.ch
                    - name: DB_NAME
                      value: kanboard
                    - name: PLUGIN_INSTALLER
                      value: true
                    - name: MAIL_FROM
                      value: kanboard@service.int.rabe.ch
                    - name: MAIL_TRANSPORT
                      value: smtp
                    - name: MAIL_SMTP_HOSTNAME
                      value: "{{ kanboard_mail_smtp_hostname }}"
                    - name: MAIL_SMTP_USERNAME
                      value: "{{ kanboard_mail_smtp_username }}"
                    - name: MAIL_SMTP_PASSWORD
                      value: "{{ kanboard_mail_smtp_password }}"
                    - name: LDAP_SERVER
                      value: "{{ kanboard_ldap_server }}"
                    - name: LDAP_BIND_TYPE
                      value: proxy
                    - name: LDAP_USERNAME
                      value: "{{ kanboard_ldap_username }}"
                    - name: LDAP_PASSWORD
                      value: "{{ kanboard_ldap_password }}"
                    - name: LDAP_USER_BASE_DN
                      value: cn=users,cn=accounts,dc=int,dc=rabe,dc=ch
                    - name: LDAP_USER_FILTER
                      value: uid=%s
                    - name: LDAP_GROUP_ADMIN_DN
                      value: cn=kanboard-admins,cn=groups,cn=accounts,dc=int,dc=rabe,dc=ch
                    - name: LDAP_GROUP_MANAGER_DN
                      value: cn=kanboard-managers,cn=groups,cn=accounts,dc=int,dc=rabe,dc=ch
                    - name: LDAP_GROUP_PROVIDER
                      value: true
                    - name: LDAP_GROUP_BASE_DN
                      value: cn=groups,cn=accounts,dc=int,dc=rabe,dc=ch
                    - name: LDAP_GROUP_FILTER
                      value: "(&(objectClass=groupofnames)(cn=%s*))"
                    - name: TRUSTED_PROXY_NETWORKS
                      value: 127.0.0.1/32,::1/128
                    - name: REVERSE_PROXY_AUTH
                      value: true
                    - name: REVERSE_PROXY_DEFAULT_ADMIN
                      value: "{{ kanboard_reverse_proxy_default_admin }}"
                    - name: REMEMBER_ME_AUTH
                      value: false
                    - name: ENABLE_URL_REWRITE
                      value: true
                    - name: HIDE_LOGIN_FORM
                      value: true
                    - name: DISABLE_LOGOUT
                      value: true
              volumes:
                - name: kanboard_data
                  hostPath:
                    path: "/home/{{ podman_run_as_user }}/data"
                    type: Directory
                - name: kanboard_plugins
                  hostPath:
                    path: "/home/{{ podman_run_as_user }}/plugins"
                    type: Directory
                - name: kanboard_ssl
                  hostPath:
                    path: "/home/{{ podman_run_as_user }}/ssl"
                    type: Directory
                - name: ca_certs
                  hostPath:
                    path: "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
                    type: File
                - name: php_fpm_ini
                  hostPath:
                    path: "/home/{{ podman_run_as_user }}/phpfpm_conf.d/z.ini"
                    type: File
    - name: podman_run_as_group
      parameter_type: string
      value: kanboard
    - name: podman_run_as_user
      parameter_type: string
      value: kanboard
    - name: podman_selinux_ports
      parameter_type: yaml
      value:
        - ports: 80
          setype: http_port_t
        - ports: 443
          setype: http_port_t
    - name: radiorabe_copies
      parameter_type: yaml
      value:
        - dest: "/home/{{ podman_run_as_user }}/phpfpm_conf.d/z.ini"
          mode: '0644'
          content: display_errors = Off
          owner: "{{ podman_run_as_user }}"
          group: "{{ podman_run_as_group }}"
    - name: radiorabe_files
      parameter_type: yaml
      value:
        - path: "/home/{{ podman_run_as_user }}/phpfpm_conf.d/"
          state: directory
          mode: '0755'
          owner: "{{ podman_run_as_user }}"
          group: "{{ podman_run_as_group }}"
    - name: selinux_booleans
      parameter_type: yaml
      value:
        - name: container_read_certs
          state: true
          persistent: true
    - name: selinux_fcontexts
      parameter_type: yaml
      value:
        - target: /etc/certmonger/post-scripts(/.*)?
          setype: certmonger_unconfined_exec_t
          ftype: f
          state: present
    - name: selinux_restore_dirs
      parameter_type: yaml
      value:
        - /etc/certmonger/post-scripts/
