---
- name: "RaBe Foreman Infrastructure : Configure Compute Resources"
  ansible.builtin.include_role:
    name: theforeman.foreman.compute_resources
  vars:
    foreman_compute_resources:
      - name: ovirt
        state: present
        description: oVirt
        organizations:
          - RaBe
        locations:
          - Randweg
        provider: ovirt
        provider_params:
          url: https://ovirt-engine-01.admin.int.rabe.ch/ovirt-engine/api
          user: foreman@ovirt@internalsso
          password: "{{ rabe_foreman_infrastructure_compute_resources_ovirt_password }}"
          # "Default" DC
          # TODO: read me from api
          datacenter: 459954c0-5d2d-4c21-9e3b-689a54d32000
          # "Default" quota
          # TODO: read me from api
          ovirt_quota: 2e50d818-c01b-4a0a-aa61-4b68cd3bb579
          use_v4: true
      - name: server-008.dmz-admin.int.rabe.ch
        state: present
        description: DMZ libvirt hypervisor server-008.dmz-admin.int.rabe.ch
        organizations:
          - RaBe
        locations:
          - Randweg
        provider: libvirt
        provider_params:
          url: qemu+ssh://root@server-008.dmz-admin.int.rabe.ch/system
        images:
          - name: AlmaLinux-9-GenericCloud-9.4-20240507.x86_64.qcow2
            operatingsystem: AlmaLinux 9
            architecture: "x86_64"
            image_username: almalinux
            user_data: true
            uuid: /var/lib/libvirt/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
      - name: server-009.dmz-admin.int.rabe.ch
        state: present
        description: DMZ libvirt hypervisor server-009.dmz-admin.int.rabe.ch
        organizations:
          - RaBe
        locations:
          - Randweg
        provider: libvirt
        provider_params:
          url: qemu+ssh://root@server-009.dmz-admin.int.rabe.ch/system
        images:
          - name: AlmaLinux-9-GenericCloud-9.4-20240507.x86_64.qcow2
            operatingsystem: AlmaLinux 9
            architecture: "x86_64"
            image_username: almalinux
            user_data: true
            uuid: /var/lib/libvirt/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
