---
- name: 'RaBe Foreman Infrastructure : Configure Compute Resources'
  ansible.builtin.include_role:
    name: theforeman.foreman.compute_resources
  vars:
    foreman_compute_resources:
      - name: ovirt
        state: present
        description: oVirt
        organizations:
          - RaBe
        locations:
          - Randweg
        provider: ovirt
        provider_params:
          url: https://ovirt-engine-01.admin.int.rabe.ch/ovirt-engine/api
          user: foreman@ovirt@internalsso
          password: '{{ rabe_foreman_infrastructure_compute_resources_ovirt_password }}'
          # "Default" DC
          # TODO: read me from api
          datacenter: 459954c0-5d2d-4c21-9e3b-689a54d32000
          # "Default" quota
          # TODO: read me from api
          ovirt_quota: 2e50d818-c01b-4a0a-aa61-4b68cd3bb579
          display_type: spice
          use_v4: true
