---
- name: "RaBe Foreman Infrastructure : Domains"
  ansible.builtin.import_tasks: domains.yml
  tags:
    - role::rabe_foreman.infrastructure
    - role::rabe_foreman.infrastructure:domains
- name: "RaBe Foreman Infrastructure : Realms"
  ansible.builtin.import_tasks: realms.yml
  tags:
    - role::rabe_foreman.infrastructure
    - role::rabe_foreman.infrastructure:realms
- name: "RaBe Foreman Infrastructure : Subnets"
  ansible.builtin.import_tasks: subnets.yml
  tags:
    - role::rabe_foreman.infrastructure
    - role::rabe_foreman.infrastructure:subnets
- name: "RaBe Foreman Infrastructure : Bootdisk"
  ansible.builtin.import_tasks: bootdisk.yml
  tags:
    - role::rabe_foreman.infrastructure
    - role::rabe_foreman.infrastructure:bootdisk
