galaxy_info:
  author: RaBe IT-Reaktion
  description: Manage Foreman Infrastructure
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-rabe_foreman/issues
  license: AGPL-3.0-only
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - foreman
dependencies:
  - radiorabe.common.base
  - radiorabe.common.core
  - radiorabe.foreman.realms
  - theforeman.foreman.compute_resources
  - theforeman.foreman.domains
