---
- name: "RaBe Foreman Config : Load Host Group from {{ _hostgroup_file | basename }}"
  ansible.builtin.include_vars:
    file: "{{ _hostgroup_file }}"

- name: "RaBe Foreman Config : Apply Host Group {{ foreman_hostgroup.name }}"
  theforeman.foreman.hostgroup:
    server_url: "{{ foreman_server_url }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ foreman_hostgroup.name }}"
    description: "{{ foreman_hostgroup.description | default(omit) }}"
    parent: "{{ foreman_hostgroup.parent | default(omit) }}"
    organization: "{{ foreman_hostgroup.organization | default(omit) }}"
    locations: "{{ foreman_hostgroup.locations | default(omit) }}"
    operatingsystem: "{{ foreman_hostgroup.operatingsystem | default(omit) }}"
    architecture: "{{ foreman_hostgroup.architecture | default(omit) }}"
    medium: "{{ foreman_hostgroup.medium | default(omit) }}"
    ptable: "{{ foreman_hostgroup.ptable | default(omit) }}"
    environment: "{{ foreman_hostgroup.environment | default(omit) }}"
    domain: "{{ foreman_hostgroup.domain | default(omit) }}"
    subnet: "{{ foreman_hostgroup.subnet | default(omit) }}"
    subnet6: "{{ foreman_hostgroup.subnet6 | default(omit) }}"
    compute_profile: "{{ foreman_hostgroup.compute_profile | default(omit) }}"
    compute_resource: "{{ foreman_hostgroup.compute_resource | default(omit) }}"
    pxe_loader: "{{ foreman_hostgroup.pxe_loader | default(omit) }}"
    lifecycle_environment: "{{ foreman_hostgroup.lifecycle_environment | default(omit) }}"
    content_view: "{{ foreman_hostgroup.content_view | default(omit) }}"
    content_source: "{{ foreman_hostgroup.content_source | default(omit) }}"
    parameters: "{{ foreman_hostgroup.parameters | default(omit) }}"
    ansible_roles: "{{ foreman_hostgroup.ansible_roles | default(omit) }}"
    state: "{{ foreman_hostgroup.state | default('present') }}"
