---
- name: 'RaBe Foreman Config : Configure Host Groups'
  ansible.builtin.include_role:
    name: theforeman.foreman.hostgroups
  vars:
    foreman_hostgroups:
      - name: RaBe Core
        description: RaBe Core contains roles that set facts and sets settings that don't
          rely on anything and are not OS specific.
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.common.core
      - name: RaBe Base
        description: RaBe Core configures the bare minimum of non OS specific things.
        parent: RaBe Core
        organization: RaBe
        location: Randweg
        architecture: x86_64
        ansible_roles:
          - radiorabe.common.base
        parameters:
          - name: foreman_scap_client_server
            parameter_type: string
            value: foreman.service.int.rabe.ch
          # base options for [zabbix](https://github.com/ansible-collections/community.zabbix) roles
          - name: zabbix_agent_server
            parameter_type: string
            value: monitoring.service.int.rabe.ch
          - name: zabbix_agent_serveractive
            parameter_type: string
            value: monitoring.service.int.rabe.ch
          - name: zabbix_repo
            parameter_type: string
            value: other
          - name: zabbix_agent_dont_detect_ip
            parameter_type: boolean
            value: true
          - name: zabbix_install_pip_packages
            parameter_type: boolean
            value: false
          # base options for [timesync](https://github.com/linux-system-roles/timesync) role
          - name: timesync_ntp_servers
            parameter_type: yaml
            value:
              - hostname: ntp-01.service.int.rabe.ch
                iburst: true
              - hostname: ntp-02.service.int.rabe.ch
                iburst: true
              - hostname: ntp-03.service.int.rabe.ch
                iburst: true
              - hostname: ntp-04.service.int.rabe.ch
                iburst: true
              - hostname: ntp-05.service.int.rabe.ch
                iburst: true
          # base options for [selinux](https://github.com/linux-system-roles/selinux) role
          - name: selinux_policy
            parameter_type: string
            value: targeted
          - name: selinux_state
            parameter_type: string
            value: enforcing
      - name: EL7
        description: EL7 configures our EL7 baseline.
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: CentOS 7
        description: CentOS 7 configures the RaBe CentOS 7 baseline and serves as a catch-all for imported CentOS 7 infrastructure.
        parent: RaBe Core/RaBe Base/EL7
        organization: RaBe
        location: Randweg
        operatingsystem: CentOS 7
      - name: EL8
        description: EL8 configures our EL8 baseline.
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: CentOS 8 Stream
        description: CentOS 8 Stream configures the RaBe CentOS 8 Stream baseline.
        parent: RaBe Core/RaBe Base/EL8
        organization: RaBe
        location: Randweg
        operatingsystem: CentOS Stream 8
        ansible_roles:
          - theforeman.foreman_scap_client
          - redhat.rhel_system_roles.kdump
          - redhat.rhel_system_roles.crypto_policies
          - redhat.rhel_system_roles.selinux
      - name: Foreman
        description: Foreman configures standalone Foreman servers.
        parent: RaBe Core/RaBe Base/EL8/CentOS 8 Stream
        organization: RaBe
        location: Randweg
      - name: EL9
        description: EL9 configures our EL9 baseline
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.rabe_foreman.client
      - name: AlmaLinux 9
        description: AlmaLinux 9.
        parent: RaBe Core/RaBe Base/EL9
        organization: RaBe
        location: Randweg
        operatingsystem: AlmaLinux 9
      - name: AlmaLinux 9 VMs
        description: AlmaLinux 9 general purpose virtual machines.
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
        organization: RaBe
        location: Randweg
        compute_resource: ovirt
