---
- name: "RaBe Foreman Config : Configure Host Groups"
  ansible.builtin.include_role:
    name: theforeman.foreman.hostgroups
  vars:
    foreman_hostgroups:
      - name: RaBe Core
        description: RaBe Core contains roles that set facts and sets settings that don't rely on anything and are not OS specific.
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.common.core
      - name: RaBe Base
        description: RaBe Core configures the bare minimum of non OS specific things.
        parent: RaBe Core
        organization: RaBe
        location: Randweg
        architecture: x86_64
        ansible_roles:
          - radiorabe.common.base
        parameters:
          - name: foreman_scap_client_server
            parameter_type: string
            value: foreman.service.int.rabe.ch
          # base options for [radiorabe.rabe_zabbix.agent](https://github.com/radiorabe/ansible-collection-rabe_zabbix/tree/main/roles/agent)
          # TODO: remove override once we are fully migrated to agent2 and we can use the default from the role
          - name: radiorabe_zabbix_agent_server
            parameter_type: string
            value: vm-0040.service.int.rabe.ch
          - name: radiorabe_zabbix_agent_serveractive
            parameter_type: string
            value: vm-0040.service.int.rabe.ch
          # base options for [timesync](https://github.com/linux-system-roles/timesync) role
          - name: timesync_ntp_servers
            parameter_type: yaml
            value:
              - hostname: ntp-01.service.int.rabe.ch
                iburst: true
              - hostname: ntp-02.service.int.rabe.ch
                iburst: true
              - hostname: ntp-03.service.int.rabe.ch
                iburst: true
              - hostname: ntp-04.service.int.rabe.ch
                iburst: true
              - hostname: ntp-05.service.int.rabe.ch
                iburst: true
          - name: time-zone
            parameter_type: string
            value: "Europe/Zurich"
          # base options for [selinux](https://github.com/linux-system-roles/selinux) role
          - name: selinux_policy
            parameter_type: string
            value: targeted
          - name: selinux_state
            parameter_type: string
            value: enforcing
          - name: subscription_manager
            parameter_type: boolean
            value: true
          - name: only_subscription_manager_repos
            parameter_type: boolean
            value: true
          - name: package_upgrade
            value: false
      - name: EL7
        description: EL7 configures our EL7 baseline.
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: CentOS 7
        description: CentOS 7 configures the RaBe CentOS 7 baseline and serves as a catch-all for imported CentOS 7 infrastructure.
        parent: RaBe Core/RaBe Base/EL7
        organization: RaBe
        location: Randweg
        operatingsystem: CentOS 7
      - name: EL8
        description: EL8 configures our EL8 baseline.
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: EL9
        description: EL9 configures our EL9 baseline
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.rabe_foreman.client
      - name: AlmaLinux 9
        description: AlmaLinux 9.
        parent: RaBe Core/RaBe Base/EL9
        organization: RaBe
        location: Randweg
        operatingsystem: AlmaLinux 9
        lifecycle_environment: Prod
        content_view: AlmaLinux 9 x86_64
        parameters:
          - name: kt_activation_keys
            parameter_type: string
            value: AlmaLinux 9
      - name: AlmaLinux 9 VMs
        description: AlmaLinux 9 general purpose virtual machines.
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
        organization: RaBe
        location: Randweg
        compute_resource: ovirt
      - name: vm-0043.service.int.rabe.ch
        description: AlmaLinux 9 VM for Letsencrypt certificate renewal on reverse proxies
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9/AlmaLinux 9 VMs
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.certbot.certbot
        parameters:
          - name: certbot_acme_account_mail
            parameter_type: string
            value: it@rabe.ch
          - name: certbot_certificates
            parameter_type: yaml
            value:
              - letest.rabe.ch
              - dmz-rev-proxy.ewb.rabe.ch
          - name: certbot_remote_hosts
            parameter_type: yaml
            value:
              - vm-2001.dmz.int.rabe.ch
              - vm-2002.dmz.int.rabe.ch
          - name: firewall
            parameter_type: yaml
            value:
              - zone: service
                state: present
                permanent: true
                immediate: true
              - zone: service
                interface: enp1s0
                state: present
                permanent: true
                immediate: true
              - zone: service
                service:
                  - cockpit
                  - ssh
                  - http
                  - pmcd
                state: enabled
                permanent: true
                immediate: true
              - set_default_zone: drop
                permanent: true
                immediate: true
      - name: AlmaLinux 9 DMZ Virtualization Server
        description: AlmaLinux 9 general purpose virtual machines.
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
        organization: RaBe
        location: Randweg
        domain: dmz-admin.int.rabe.ch
        subnet: dmz-admin
        ansible_roles:
          - redhat.rhel_system_roles.network
          - radiorabe.foreman_libvirt.libvirt
          - radiorabe.common.download_file
        parameters:
          - name: download_file_destination
            parameter_type: string
            value: /var/lib/libvirt/images/
          - name: download_file_url
            parameter_type: string
            value: https://foreman.service.int.rabe.ch/pulp/content/RaBe/Library/custom/AlmaLinux_OS_Generic_Cloud_Cloud-init_image/AlmaLinux_OS_Generic_Cloud_Cloud-init_image/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
          - name: remote_execution_ssh_keys
            parameter_type: string
            value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4arUJdueCQnOkjVOvrruEEs9M/lKw2ITorTTEIIFgcNAGZNs+SFFxugtMWY2jzrcHoxwSZel3eAMjvS76by6z3ZqZUvMxVHACR0FZvP2WtLk2BjgDjYdmBGDpMArvncHkaiVtjEaruwXVqO+64qsrYXQ3qhUiah+9soFHghWZWS3i+Dnd1JiNFX6TZP+ooqshBaClspAfcywsqFhsFNeU50rlsl11T13vLmZ/G140VF7uhaZ2ukOEj3HSSBcQ1DKIyanoo4fpAG8ealo6Nur0t5rlO67ACgRjLIVBS0LnVG5tvXtnKbz6A0uoUHC5aesDnDUskImWiKnz/6r2QenMkzD08BT6VlaFHhpp4ve2/d2lmjAl4EXvNOCwGsGV9A5BB1O130dwRk85Cxutxm94tuThElWlu37BB8pxOYz8qD+Vph5TVbC4mi1/30hUQffll0x/mcplJsFLY9H7eX0S+Ki2W++udWQ4HfwxbxXlJltMLEw7fhSxEQdGNfIaoM0= foreman@foreman.service.int.rabe.ch
          - name: network_connections
            parameter_type: yaml
            value:
              - name: Bond bond0
                state: up
              - name: dmz
                interface_name: dmz
                type: bridge
                ip:
                  dhcp4: false
                  auto6: false
              - name: Vlan bond0.133
                interface_name: bond0.133
                type: vlan
                vlan:
                  id: "133"
                parent: Bond bond0
                controller: dmz
                port_type: bridge
      - name: AlmaLinux 9 DMZ server-008 VMs
        description: AlmaLinux 9 virtual machines to be run on server-008
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
        organization: RaBe
        location: Randweg
        domain: dmz.int.rabe.ch
        subnet: dmz
        compute_resource: server-008.dmz-admin.int.rabe.ch
        compute_profile: "1-Small"
      - name: vm-2001.dmz.int.rabe.ch
        description: AlmaLinux 9 DMZ virtual machine vm-2001 for running reverse-proxy container
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9/AlmaLinux 9 DMZ server-009 VMs
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.common.local_user
          - redhat.rhel_system_roles.podman
        parameters:
          - name: firewall
            parameter_type: yaml
            value:
              - service: http-alt
                port: 8080/tcp
                state: present
                permanent: true
              - service: https-alt
                port: 8443/tcp
                state: present
                permanent: true
              - zone: dmz
                interface: eth0
                state: present
                permanent: true
              - zone: dmz
                state: enabled
                permanent: true
                service:
                  - cockpit
                  - ssh
                  - http-alt
                  - https-alt
                  - pmcd
          - name: local_user_username
            parameter_type: string
            value: revproxy
          - name: podman_create_host_directories
            parameter_type: boolean
            value: true
          - name: podman_firewall
            parameter_type: yaml
            value:
              - port: 8080/tcp
                state: enabled
              - port: 8090/tcp
                state: enabled
              - port: 8443/tcp
                state: enabled
          - name: podman_kube_specs
            parameter_type: yaml
            value:
              - state: started
                kube_file_content:
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    name: revproxy
                  spec:
                    containers:
                      - name: revproxy
                        image: ghcr.io/radiorabe/httpd:0.5.1
                        env:
                          - name: PODMAN_HOST
                            value: "{{ ansible_host }}"
                        ports:
                          - containerPort: 8080
                            hostPort: 8080
                          - containerPort: 8090
                            hostPort: 8090
                          - containerPort: 8443
                            hostPort: 8443
                        volumeMounts:
                          - mountPath: "/etc/httpd/conf.d/local_configs:Z"
                            name: local_httpd_configs
                          - mountPath: "/etc/httpd/modsecurity.d/local_rules:Z"
                            name: local_modsec_rules
                          - mountPath: "/etc/pki/tls/private/rabe_certs:Z"
                            name: local_letsencrypt_certs
                    volumes:
                      - name: local_httpd_configs
                        hostPath:
                          path: "/home/revproxy/httpd/conf.d/local_configs"
                      - name: local_modsec_rules
                        hostPath:
                          path: "/home/revproxy/httpd/modsecurity.d/local_rules"
                      - name: local_letsencrypt_certs
                        hostPath:
                          path: "/home/revproxy/httpd/rabe_certs"
          - name: podman_run_as_group
            parameter_type: string
            value: revproxy
          - name: podman_run_as_user
            parameter_type: string
            value: revproxy
          - name: podman_selinux_ports
            parameter_type: yaml
            value:
              - ports: 8080
                setype: http_port_t
              - ports: 8090
                setype: http_port_t
              - ports: 8443
                setype: http_port_t
          - name: podman_containers_conf
            parameter_type: yaml
            value:
              containers:
                log_size_max: 1073741824 # 1Gib in bytes
      - name: AlmaLinux 9 DMZ server-009 VMs
        description: AlmaLinux 9 virtual machines to be run on server-009
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
        organization: RaBe
        location: Randweg
        domain: dmz.int.rabe.ch
        subnet: dmz
        compute_resource: server-009.dmz-admin.int.rabe.ch
        compute_profile: "1-Small"
      - name: vm-2002.dmz.int.rabe.ch
        description: AlmaLinux 9 DMZ virtual machine vm-2002 for running reverse-proxy container
        parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9/AlmaLinux 9 DMZ server-009 VMs
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.common.local_user
          - redhat.rhel_system_roles.podman
        parameters:
          - name: firewall
            parameter_type: yaml
            value:
              - service: http-alt
                port: 8080/tcp
                state: present
                permanent: true
              - service: https-alt
                port: 8443/tcp
                state: present
                permanent: true
              - zone: dmz
                interface: eth0
                state: present
                permanent: true
              - zone: dmz
                state: enabled
                permanent: true
                service:
                  - cockpit
                  - ssh
                  - http-alt
                  - https-alt
                  - pmcd
          - name: local_user_username
            parameter_type: string
            value: revproxy
          - name: podman_create_host_directories
            parameter_type: boolean
            value: true
          - name: podman_firewall
            parameter_type: yaml
            value:
              - port: 8080/tcp
                state: enabled
              - port: 8090/tcp
                state: enabled
              - port: 8443/tcp
                state: enabled
          - name: podman_kube_specs
            parameter_type: yaml
            value:
              - state: started
                kube_file_content:
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    name: revproxy
                  spec:
                    containers:
                      - name: revproxy
                        image: ghcr.io/radiorabe/httpd:0.5.1
                        env:
                          - name: PODMAN_HOST
                            value: "{{ ansible_host }}"
                        ports:
                          - containerPort: 8080
                            hostPort: 8080
                          - containerPort: 8090
                            hostPort: 8090
                          - containerPort: 8443
                            hostPort: 8443
                        volumeMounts:
                          - mountPath: "/etc/httpd/conf.d/local_configs:Z"
                            name: local_httpd_configs
                          - mountPath: "/etc/httpd/modsecurity.d/local_rules:Z"
                            name: local_modsec_rules
                          - mountPath: "/etc/pki/tls/private/rabe_certs:Z"
                            name: local_letsencrypt_certs
                    volumes:
                      - name: local_httpd_configs
                        hostPath:
                          path: "/home/revproxy/httpd/conf.d/local_configs"
                      - name: local_modsec_rules
                        hostPath:
                          path: "/home/revproxy/httpd/modsecurity.d/local_rules"
                      - name: local_letsencrypt_certs
                        hostPath:
                          path: "/home/revproxy/httpd/rabe_certs"
          - name: podman_run_as_group
            parameter_type: string
            value: revproxy
          - name: podman_run_as_user
            parameter_type: string
            value: revproxy
          - name: podman_selinux_ports
            parameter_type: yaml
            value:
              - ports: 8080
                setype: http_port_t
              - ports: 8090
                setype: http_port_t
              - ports: 8443
                setype: http_port_t
          - name: podman_containers_conf
            parameter_type: yaml
            value:
              containers:
                log_size_max: 1073741824 # 1Gib in bytes
