---
- name: "RaBe Foreman Config : Configure Host Groups"
  ansible.builtin.include_tasks: host_group.yaml
  loop: "{{ query('fileglob', role_path ~ '/vars/hostgroups/*.yaml') | sort }}"
  loop_control:
    loop_var: _hostgroup_file
    label: "{{ _hostgroup_file | basename }}"
