---
- name: 'RaBe Foreman Config : Job Templates'
  block:
    - name: 'RaBe Foreman Config : Unlock All Job Templates'
      ansible.builtin.include_role:
        name: radiorabe.foreman.job_templates
      vars:
        foreman_job_templates:
          - name: '*'
            locked: false
      when: not ansible_check_mode
    - name: 'RaBe Foreman Config : Configure Job Templates'
      ansible.builtin.include_role:
        name: radiorabe.foreman.job_templates
      vars:
        foreman_job_templates:
          - name: Manage Windows Updates - Ansible Default
            state: absent
          - name: Configure Cloud Connector
            state: absent
          - name: Convert to RHEL
            state: absent
          - name: Puppet Agent Disable - Script Default
            state: absent
          - name: Puppet Agent Enable - Script Default
            state: absent
          - name: Puppet Module - Install from forge - Script Default
            state: absent
          - name: Puppet Module - Install from git - Script Default
            state: absent
          - name: Puppet Run Once - Ansible Default
            state: absent
          - name: Puppet Run Once - Script Default
            state: absent
          # can be removed after 0.34.1 has been applied
          - name: RaBe Foreman - Publish Content View
            state: absent
          - name: RaBe Foreman - Publish Content Views
            state: present
            job_category: RaBe Foreman
            description_format: RaBe Foreman - Publish Content Views
            snippet: false
            provider_type: Ansible
            kind: job_template
            model: JobTemplate
            file_name: '{{ role_path }}/../../../rabe_foreman/roles/foreman/files/job_templates/rabe_foreman_publish_content_view.erb'
          - name: RaBe Foreman - Promote Content Views to Prod
            state: present
            job_category: RaBe Foreman
            description_format: RaBe Foreman - Promote Content Views to Prod
            snippet: false
            template_inputs:
              - name: lifecycle_environment
                required: true
                input_type: user
                description: |-
                  Target Environment.
                advanced: true
                default: Prod
            provider_type: Ansible
            kind: job_template
            model: JobTemplate
            file_name: '{{ role_path }}/../../../rabe_foreman/roles/foreman/files/job_templates/rabe_foreman_promote_content_views.erb'
          - name: RaBe Foreman - Version Cleanup Content Views
            state: present
            job_category: RaBe Foreman
            description_format: RaBe Foreman - Version Cleanup Content Views
            snippet: false
            provider_type: Ansible
            kind: job_template
            model: JobTemplate
            file_name: '{{ role_path }}/../../../rabe_foreman/roles/foreman/files/job_templates/rabe_foreman_version_cleanup_content_view.erb'
      when: not ansible_check_mode
  always:
    - name: 'RaBe Foreman Config : Lock All Job Templates'
      ansible.builtin.include_role:
        name: radiorabe.foreman.job_templates
      vars:
        foreman_job_templates:
          - name: '*'
            locked: true
      when: not ansible_check_mode
