---
- name: "RaBe Foreman Config : Configure Locations"
  ansible.builtin.include_role:
    name: radiorabe.foreman.locations
  vars:
    foreman_locations:
      - name: Randweg
        organizations:
          - RaBe
