---
- name: 'radiorabe.rabe_foreman.foreman : Organizations'
  ansible.builtin.import_tasks: organizations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:organizations
- name: 'radiorabe.rabe_foreman.foreman : Locations'
  ansible.builtin.import_tasks: locations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:locations
- name: 'radiorabe.rabe_foreman.foreman : Settings'
  ansible.builtin.import_tasks: settings.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:settings
- name: 'radiorabe.rabe_foreman.foreman : Roles'
  ansible.builtin.import_tasks: roles.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:roles
- name: 'radiorabe.rabe_foreman.foreman : Global Parameters'
  ansible.builtin.import_tasks: global_parameters.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:global_parameters
- name: 'radiorabe.rabe_foreman.foreman : Host Groups'
  ansible.builtin.import_tasks: host_groups.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:host_groups
- name: 'radiorabe.rabe_foreman.foreman : Job Templates'
  ansible.builtin.import_tasks: job_templates.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:job_templates
