---
- name: Configure Foreman Organizations
  ansible.builtin.include_role:
    name: theforeman.foreman.organizations
  vars:
    foreman_organizations:
      - name: RaBe
        state: present
        description: Radio Bern RaBe

- name: Configure Foreman Locations
  ansible.builtin.include_role:
    name: radiorabe.foreman.locations
  vars:
    foreman_locations:
      - name: Randweg
        organizations:
          - RaBe

- name: Configure Foreman Settings
  ansible.builtin.include_role:
    name: theforeman.foreman.settings
  vars:
    foreman_settings:
      - name: rss_enable
        value: false
      - name: administrator
        value: it@rabe.ch
      - name: email_reply_address
        value: noreply@rabe.ch
      - name: ansible_roles_to_ignore
        value:
          - linux-system-roles.*
          - rhel-system-roles.*
      - name: lab_features
        value: false

- name: Configure Foreman Global Parameters
  ansible.builtin.include_role:
    name: radiorabe.foreman.global_parameters
  vars:
    foreman_global_parameters:
      - name: ansible_roles_check_mode
        parameter_type: boolean
        value: false
      - name: host_packages
        value: ""
      - name: host_registration_insights
        parameter_type: boolean
        value: false
      - name: host_registration_remote_execution
        parameter_type: boolean
        value: true
