---
- name: 'radiorabe.rabe_foreman.foreman : Configure Organizations'
  ansible.builtin.include_role:
    name: theforeman.foreman.organizations
  vars:
    foreman_organizations:
      - name: RaBe
        state: present
        description: Radio Bern RaBe

- name: 'radiorabe.rabe_foreman.foreman : Configure Locations'
  ansible.builtin.include_role:
    name: radiorabe.foreman.locations
  vars:
    foreman_locations:
      - name: Randweg
        organizations:
          - RaBe

- name: 'radiorabe.rabe_foreman.foreman : Configure Settings'
  ansible.builtin.include_role:
    name: theforeman.foreman.settings
  vars:
    foreman_settings:
      - name: rss_enable
        value: false
      - name: administrator
        value: it@rabe.ch
      - name: email_reply_address
        value: noreply@rabe.ch
      - name: ansible_roles_to_ignore
        value:
          - linux-system-roles.*
          - rhel-system-roles.*
      - name: lab_features
        value: false

- name: 'radiorabe.rabe_foreman.foreman : Configure Roles'
  ansible.builtin.include_role:
    name: radiorabe.foreman.roles
  vars:
    foreman_roles:
      - name: Default role
        description: Role that is automatically assigned to every user in the system. Adding
          a permission grants it to everybody
        state: present
        filters:
          - permissions:
              - view_foreman_tasks
            search: owner.id = current_user
          - permissions:
              - view_job_invocations
            search: user = current_user

- name: 'radiorabe.rabe_foreman.foreman : Configure Global Parameters'
  ansible.builtin.include_role:
    name: radiorabe.foreman.global_parameters
  vars:
    foreman_global_parameters:
      - name: ansible_roles_check_mode
        parameter_type: boolean
        value: false
      - name: host_packages
        value: ""
      - name: host_registration_insights
        parameter_type: boolean
        value: false
      - name: host_registration_remote_execution
        parameter_type: boolean
        value: true

- name: 'radiorabe.rabe_foreman.foreman : Configure Host Groups'
  ansible.builtin.include_role:
    name: theforeman.foreman.hostgroups
  vars:
    foreman_hostgroups:
      - name: RaBe Core
        description: RaBe Core contains roles that set facts and sets settings that don't
          rely on anything and are not OS specific.
        organization: RaBe
        location: Randweg
        ansible_roles:
          - radiorabe.common.core
      - name: RaBe Base
        description: RaBe Core configures the bare minimum of non OS specific things.
        parent: RaBe Core
        organization: RaBe
        location: Randweg
      - name: EL8
        description: EL8 configures our EL8 baseline
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: CentOS 8 Stream
        description: CentOS 8 Stream configures the RaBe CentOS 8 Stream baseline
        parent: RaBe Core/RaBe Base/EL8
        organization: RaBe
        location: Randweg
        ansible_roles:
          - theforeman.foreman_scap_client
          - redhat.rhel_system_roles.kdump
          - redhat.rhel_system_roles.crypto_policies
      - name: Foreman
        description: Foreman configures standalone Foreman servers.
        parent: RaBe Core/RaBe Base/EL8/CentOS 8 Stream
        organization: RaBe
        location: Randweg
      - name: EL9
        description: EL9 configures our EL9 baseline
        parent: RaBe Core/RaBe Base
        organization: RaBe
        location: Randweg
      - name: AlmaLinux 9
        description: AlmaLinux 9.
        parent: RaBe Core/RaBe Base/EL9
        organization: RaBe
        location: Randweg
