---
- name: 'RaBe Foreman Config : Organizations'
  ansible.builtin.import_tasks: organizations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:organizations
- name: 'RaBe Foreman Config : Locations'
  ansible.builtin.import_tasks: locations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:locations
- name: 'RaBe Foreman Config : Settings'
  ansible.builtin.import_tasks: settings.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:settings
- name: 'RaBe Foreman Config : Roles'
  ansible.builtin.import_tasks: roles.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:roles
- name: 'RaBe Foreman Config : Global Parameters'
  ansible.builtin.import_tasks: global_parameters.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:global_parameters
- name: 'RaBe Foreman Config : Host Groups'
  ansible.builtin.import_tasks: host_groups.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:host_groups
- name: 'RaBe Foreman Config : Job Templates'
  ansible.builtin.import_tasks: job_templates.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:job_templates
