---
- ansible.builtin.import_tasks: organizations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:organizations
- ansible.builtin.import_tasks: locations.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:locations
- ansible.builtin.import_tasks: settings.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:settings
- ansible.builtin.import_tasks: roles.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:roles
- ansible.builtin.import_tasks: global_parameters.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:global_parameters
- ansible.builtin.import_tasks: host_groups.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:host_groups
- ansible.builtin.import_tasks: job_templates.yaml
  tags:
    - role::rabe_foreman.foreman
    - role::rabe_foreman.foreman:job_templates
