---
- name: "RaBe Foreman Patches : Get REX engine file location"
  ansible.builtin.shell: 'set -o pipefail && gem contents foreman_remote_execution | grep "engine.rb$"'
  register: foreman_rex_engine_cmd
  changed_when: false
- name: 'RaBe Foreman Patches : Remove "Run Puppet Once" from hostpage'
  ansible.builtin.lineinfile:
    path: "{{ foreman_rex_engine_cmd.stdout }}"
    regexp: "^      :host_action_button => (true|false)$"
    line: "      :host_action_button => false"
  when: (foreman_rex_engine_cmd.stdout is defined) and (foreman_rex_engine_cmd.stdout)
