---
- name: 'radiorabe.rabe_foreman.foreman : Configure Roles'
  ansible.builtin.include_role:
    name: radiorabe.foreman.roles
  vars:
    foreman_roles:
      - name: Default role
        description: Role that is automatically assigned to every user in the system. Adding
          a permission grants it to everybody
        state: present
        filters:
          - permissions:
              - view_foreman_tasks
            search: owner.id = current_user
          - permissions:
              - view_job_invocations
            search: user = current_user
