---
- name: 'RaBe Foreman Config : Configure Settings'
  ansible.builtin.include_role:
    name: theforeman.foreman.settings
  vars:
    foreman_settings:
      - name: rss_enable
        value: false
      - name: administrator
        value: '{{ radiorabe_core_admin_mail }}'
      - name: email_reply_address
        value: '{{ radiorabe_base_mail_noreply }}'
      - name: ansible_roles_to_ignore
        value:
          - linux-system-roles.*
          - rhel-system-roles.*
      - name: lab_features
        value: false
