---
# TODO: figure out how disable repos by default and get rid of overrides here
- name: "RaBe Foreman Content : Configure Activation Keys"
  ansible.builtin.include_role:
    name: theforeman.foreman.activation_keys
  vars:
    foreman_activation_keys:
      - name: "AlmaLinux 9"
        lifecycle_environment: "Prod"
        content_view: "AlmaLinux 9 x86_64"
        content_overrides:
          - label: RaBe_alma9_alma9_baseos
            override: enabled
          - label: RaBe_alma9_alma9_extras
            override: enabled
          - label: RaBe_alma9_alma9_appstream
            override: enabled
          - label: RaBe_alma9_alma9_baseos_kickstart
            override: disabled
          - label: RaBe_alma9_alma9_appstream_kickstart
            override: disabled
          - label: RaBe_alma9_alma9_rt
            override: disabled
          - label: RaBe_alma9_alma9_resilientstorage
            override: disabled
          - label: RaBe_epel9_epel9
            override: disabled
          - label: RaBe_alma9_alma9_ha
            override: disabled
          - label: RaBe_alma9_alma9_plus
            override: disabled
          - label: RaBe_alma9_alma9_crb
            override: disabled
          - label: RaBe_alma9_alma9_nfv
            override: disabled
          - label: RaBe_rabeel9_rabeel9_rabezabbix
            override: enabled
          - label: RaBe_zabbix70_zabbix70
            override: enabled
      - name: "CentOS 7"
        lifecycle_environment: "Prod"
        content_view: "CentOS 7 x86_64"
        content_overrides:
          - label: RaBe_c7_c7_os
            override: enabled
          - label: RaBe_c7_c7_updates
            override: enabled
          - label: RaBe_c7_c7_extras
            override: enabled
          - label: RaBe_c7_c7_fasttrack
            override: disabled
          - label: RaBe_c7_c7_plus
            override: disabled
          - label: RaBe_c7_c7_sclorh
            override: disabled
          - label: RaBe_c7_c7_sclo
            override: disabled
          # disable both until end of migration
          - label: RaBe_c7_c7_storage_glusterfs312
            override: disabled
          - label: RaBe_c7_c7_storage_glusterfs10
            override: disabled
          - label: RaBe_epel7_epel7
            override: disabled
          # disable modern zabbix until we update our server
          - label: RaBe_zabbix60el7_zabbix60el7
            override: disabled
          # disable postgresql repos per default as they are only for servers
          - label: RaBe_pgdg16el7_pgdg16el7_common
            override: disabled
          - label: RaBe_pgdg16el7_pgdg16el7_extras
            override: disabled
          - label: RaBe_pgdg16el7_pgdg16el7_pgdg15
            override: disabled
