---
- name: 'RaBe Foreman Content : Configure Content Views'
  ansible.builtin.include_role:
    name: theforeman.foreman.content_views
  vars:
    foreman_content_views:
      # First, we define some views for all of our base repos
      - name: CentOS 7 Base x86_64
        repositories:
          - name: CentOS 7 OS x86_64
            product: CentOS 7
          - name: CentOS 7 Extras x86_64
            product: CentOS 7
          - name: CentOS 7 FastTrack x86_64
            product: CentOS 7
          - name: CentOS 7 Plus x86_64
            product: CentOS 7
          - name: CentOS 7 Updates x86_64
            product: CentOS 7
          - name: Extra Packages for Enterprise Linux 7 x86_64
            product: CentOS 7
          - name: Foreman Client 3.4 EL7 x86_64
            product: Foreman Client 3.4 EL7
      - name: AlmaLinux 9 Base x86_64
        repositories:
          - name: AlmaLinux 9 BaseOS x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 AppStream x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 CRB x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 Extras x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 HighAvailability x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 NFV x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 Plus x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 ResilientStorage x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 RT x86_64
            product: AlmaLinux 9
          - name: Foreman Client 3.4 EL9 x86_64
            product: Foreman Client 3.4 EL9
          - name: Extra Packages for Enterprise Linux 9 x86_64
            product: Extra Packages for Enterprise Linux 9
      # Next are all non os, but enterprise linux specific content views.
      # These will often be filtered to only contain packages we want in
      # our downstream composite views.
      - name: Zabbix 6.0 Agent EL7 x86_64
        repositories:
          - name: Zabbix 6.0 Official Repository - EL7 - x86_64
            product: Zabbix 6.0 (LTS) EL7
        filters:
          - name: zabbix-agent
            filter_state: present
            filter_type: rpm
            rule_name: zabbix-agent
            package_name: zabbix-agent
            inclusion: true
      - name: Zabbix 6.0 Agent EL8 x86_64
        repositories:
          - name: Zabbix 6.0 Official Repository - EL8 - x86_64
            product: Zabbix 6.0 (LTS) EL8
        filters:
          - name: zabbix-agent
            filter_state: present
            filter_type: rpm
            rule_name: zabbix-agent
            package_name: zabbix-agent
            inclusion: true
      - name: Zabbix 6.0 Agent EL9 x86_64
        repositories:
          - name: Zabbix 6.0 Official Repository - EL9 - x86_64
            product: Zabbix 6.0 (LTS) EL9
        filters:
          - name: zabbix-agent
            filter_state: present
            filter_type: rpm
            rule_name: zabbix-agent
            package_name: zabbix-agent
            inclusion: true
      # finally, we create composite views that combine base operating systems
      # with any additional repos that are always part of an installation. These
      # are also the content views that will have activation keys assigned.
      - name: CentOS 7 x86_64
        components:
          - content_view: CentOS 7 Base x86_64
            latest: true
          - content_view: Zabbix 6.0 Agent EL7 x86_64
            latest: true
      - name: AlmaLinux 9 x86_64
        components:
          - content_view: AlmaLinux 9 Base x86_64
            latest: true
          - content_view: Zabbix 6.0 Agent EL9 x86_64
            latest: true
