---
- name: 'RaBe Foreman Content : Configure Content Views'
  ansible.builtin.include_role:
    name: theforeman.foreman.content_views
  vars:
    foreman_content_views:
      # First, we define some views for all of our base repos
      - name: CentOS 7 Base x86_64
        repositories:
          - name: CentOS 7 OS x86_64
            product: CentOS 7
          - name: CentOS 7 Extras x86_64
            product: CentOS 7
          - name: CentOS 7 FastTrack x86_64
            product: CentOS 7
          - name: CentOS 7 Plus x86_64
            product: CentOS 7
          - name: CentOS 7 Updates x86_64
            product: CentOS 7
          - name: CentOS 7 SCLo-rh x86_64
            product: CentOS 7
          - name: CentOS 7 SCLo-sclo x86_64
            product: CentOS 7
          - name: CentOS 7 Storage GlusterFS 3.12 x86_64
            product: CentOS 7
          - name: CentOS 7 Storage GlusterFS 10 x86_64
            product: CentOS 7
          - name: Extra Packages for Enterprise Linux 7 x86_64
            product: Extra Packages for Enterprise Linux 7
          - name: Foreman Client 3.10 EL7 x86_64
            product: Foreman Client 3.10 EL7
          - name: RaBe Logstash Addons EL7
            product: RaBe Logstash Addons EL7
          - name: Copr repo for rabe-zabbix x86_64
            product: RaBe Linux EL7
          - name: Broadcast Applications from Paravel Systems
            product: Paravel Systems EL7
          - name: Commercial Applications from Paravel Systems
            product: Paravel Systems EL7
          - name: RaBe Liquidsoap Distribution for EL7
            product: RaBe Liquidsoap Distribution for EL7
          - name: LibreTime 2.5.x
            product: LibreTime EL7
          - name: RaBe Audio EL7
            product: RaBe Audio EL7
          - name: Nux Dextop EL7
            product: Nux Dextop EL7
          - name: Zabbix 6.4 Official Repository - EL7 - x86_64
            product: Zabbix 6.4 EL7
          - name: PostgreSQL common RPMs for EL7
            product: PostgreSQL 15 EL7
          - name: PostgreSQL extra RPMs for EL7
            product: PostgreSQL 15 EL7
          - name: PostgreSQL 15 for EL7
            product: PostgreSQL 15 EL7
          - name: Trivy for EL7 (x84_64)
            product: Trivy
      - name: AlmaLinux 8 Base x86_64
        repositories:
          - name: AlmaLinux 8 BaseOS x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 BaseOS Kickstart x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 AppStream x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 AppStream Kickstart x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 PowerTools x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 Extras x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 HighAvailability x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 NFV x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 Plus x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 ResilientStorage x86_64
            product: AlmaLinux 8
          - name: AlmaLinux 8 RT x86_64
            product: AlmaLinux 8
          - name: Foreman Client 3.10 EL8 x86_64
            product: Foreman Client 3.10 EL8
          - name: Extra Packages for Enterprise Linux 8 x86_64
            product: Extra Packages for Enterprise Linux 8
      - name: AlmaLinux 9 Base x86_64
        repositories:
          - name: AlmaLinux 9 BaseOS x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 BaseOS Kickstart x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 AppStream x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 AppStream Kickstart x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 CRB x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 Extras x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 HighAvailability x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 NFV x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 Plus x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 ResilientStorage x86_64
            product: AlmaLinux 9
          - name: AlmaLinux 9 RT x86_64
            product: AlmaLinux 9
          - name: Foreman Client 3.10 EL9 x86_64
            product: Foreman Client 3.10 EL9
          - name: Extra Packages for Enterprise Linux 9 x86_64
            product: Extra Packages for Enterprise Linux 9
          - name: Zabbix 6.4 Official Repository - EL9 - x86_64
            product: Zabbix 6.4 EL9
          - name: Zabbix Official Repository (non-supported) - EL9 - x86_64
            product: Zabbix 6.4 EL9
          - name: Trivy for EL9 (x84_64)
            product: Trivy
      # Next are all non os, but enterprise linux specific content views.
      # These will often be filtered to only contain packages we want in
      # our downstream composite views.
      - name: Zabbix 3.0 Agent EL7 x86_64
        repositories:
          - name: Zabbix 3.0 Official Repository - EL7 - x86_64
            product: Zabbix 3.0 (LTS) EL7
        filters:
          - name: zabbix-agent
            filter_state: present
            filter_type: rpm
            rule_name: zabbix-agent
            package_name: zabbix-agent
            inclusion: true
          - name: zabbix-sender
            filter_state: present
            filter_type: rpm
            rule_name: zabbix-sender
            package_name: zabbix-sender
            inclusion: true
      # finally, we create composite views that combine base operating systems
      # with any additional repos that are always part of an installation. These
      # are also the content views that will have activation keys assigned.
      - name: CentOS 7 x86_64
        components:
          - content_view: CentOS 7 Base x86_64
            latest: true
          - content_view: Zabbix 3.0 Agent EL7 x86_64
            latest: true
      - name: AlmaLinux 9 x86_64
        components:
          - content_view: AlmaLinux 9 Base x86_64
            latest: true
