---
- name: 'RaBe Foreman Content : Configure Products'
  ansible.builtin.include_role:
    name: theforeman.foreman.repositories
  vars:
    foreman_products:
      # Products for all base operating systems get defined first.
      - name: CentOS 7
        label: c7
        repositories:
          - name: CentOS 7 OS x86_64
            content_type: yum
            label: c7_os
            url: http://mirror.centos.org/centos/7/os/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Extras x86_64
            content_type: yum
            label: c7_extras
            url: http://mirror.centos.org/centos/7/extras/x86_64/
            download_policy: on_demand
          - name: CentOS 7 FastTrack x86_64
            content_type: yum
            label: c7_fasttrack
            url: http://mirror.centos.org/centos/7/fasttrack/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Plus x86_64
            content_type: yum
            label: c7_plus
            url: http://mirror.centos.org/centos/7/centosplus/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS 7 Updates x86_64
            content_type: yum
            label: c7_updates
            url: http://mirror.centos.org/centos/7/updates/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS 7 SCLo-rh x86_64
            content_type: yum
            label: c7_sclorh
            url: http://mirror.centos.org/centos/7/sclo/x86_64/rh/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS 7 SCLo-sclo x86_64
            content_type: yum
            label: c7_sclo
            url: http://mirror.centos.org/centos/7/sclo/x86_64/sclo/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS 7 Storage GlusterFS 3.12 x86_64
            content_type: yum
            label: c7_storage_glusterfs312
            url: http://mirror.centos.org/centos/7/storage/x86_64/gluster-3.12/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS 7 Storage GlusterFS 10 x86_64
            content_type: yum
            label: c7_storage_glusterfs10
            url: http://mirror.centos.org/centos/7/storage/x86_64/gluster-10/
            download_policy: on_demand
            auto_enabled: false
      - name: CentOS 8 Stream
        label: cs8s
        repositories:
          - name: CentOS Stream 8 BaseOS x86_64
            content_type: yum
            label: cs8s_baseos
            url: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 AppStream x86_64
            content_type: yum
            label: cs8s_appstream
            url: http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 Extras x86_64
            content_type: yum
            label: cs8s_extras
            url: http://mirror.centos.org/centos/8-stream/extras/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 PowerTools x86_64
            content_type: yum
            label: cs8s_powertools
            url: http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS Stream 8 RealTime x86_64
            content_type: yum
            label: cs8s_rt
            url: http://mirror.centos.org/centos/8-stream/RT/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS Stream 8 HighAvailability x86_64
            content_type: yum
            label: cs8s_ha
            url: http://mirror.centos.org/centos/8-stream/HighAvailability/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS Stream 8 ResilientStorage x86_64
            content_type: yum
            label: cs8s_resilientstorage
            url: http://mirror.centos.org/centos/8-stream/ResilientStorage/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS Stream 8 NFV x86_64
            content_type: yum
            label: cs8s_nfv
            url: http://mirror.centos.org/centos/8-stream/NFV/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: CentOS Stream 8 Foreman client 3.4 x86_64
            content_type: yum
            label: cs8s_foreman34_client
            url: https://yum.theforeman.org/client/3.4/el8/x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: AlmaLinux 9
        label: alma9
        repositories:
          - name: AlmaLinux 9 BaseOS x86_64
            content_type: yum
            label: alma9_baseos
            url: https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 AppStream x86_64
            content_type: yum
            label: alma9_appstream
            url: https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 CRB x86_64
            content_type: yum
            label: alma9_crb
            url: https://repo.almalinux.org/almalinux/9/CRB/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: AlmaLinux 9 Extras x86_64
            content_type: yum
            label: alma9_extras
            url: https://repo.almalinux.org/almalinux/9/extras/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 HighAvailability x86_64
            content_type: yum
            label: alma9_ha
            url: https://repo.almalinux.org/almalinux/9/HighAvailability/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: AlmaLinux 9 NFV x86_64
            content_type: yum
            label: alma9_nfv
            url: https://repo.almalinux.org/almalinux/9/NFV/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: AlmaLinux 9 Plus x86_64
            content_type: yum
            label: alma9_plus
            url: https://repo.almalinux.org/almalinux/9/plus/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: AlmaLinux 9 ResilientStorage x86_64
            content_type: yum
            label: alma9_resilientstorage
            url: https://repo.almalinux.org/almalinux/9/ResilientStorage/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
          - name: AlmaLinux 9 RT x86_64
            content_type: yum
            label: alma9_rt
            url: https://repo.almalinux.org/almalinux/9/RT/x86_64/os/
            download_policy: on_demand
            auto_enabled: false
      # The Foreman product is here for safe-keeping but not currently used anywhere (ie. Foreman
      # does not manage it's own content (yet?)).
      - name: Foreman
        label: theforeman
        repositories:
          - name: CentOS Configmanagement SIG - ansible-29
            label: centos-ansible-29
            content_type: yum
            download_policy: on_demand
            url: http://mirror.centos.org/centos/8/configmanagement/x86_64/ansible-29/
          - name: Ansible runner
            label: ansible-runner
            content_type: yum
            download_policy: on_demand
            url: https://releases.ansible.com/ansible-runner/rpm/epel-8-x86_64/
          - name: Foreman 3.3
            state: absent
            label: foreman33
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/releases/3.3/el8/x86_64/
          - name: Foreman plugins 3.3
            state: absent
            label: foreman33-plugins
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/plugins/3.3/el8/x86_64/
          - name: Foreman 3.4
            label: foreman34
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/releases/3.4/el8/x86_64/
          - name: Foreman plugins 3.4
            label: foreman34-plugins
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/plugins/3.4/el8/x86_64/
          - name: Katello 4.5
            state: absent
            label: katello45
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.5/katello/el8/x86_64/
          - name: Katello 4.6
            label: katello46
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.6/katello/el8/x86_64/
          - name: 'Candlepin: an open source entitlement management system.'
            label: katello45-candlepin
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.5/candlepin/el8/x86_64/
          - name: 'pulpcore: Fetch, Upload, Organize, and Distribute Software Packages.'
            label: pulpcore
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/pulpcore/3.18/el8/x86_64/
          - name: Puppet 7 Repository el 8 - x86_64
            label: puppet7
            content_type: yum
            download_policy: on_demand
            url: http://yum.puppetlabs.com/puppet7/el/8/x86_64/
      # A copy of our Ansible collections for safe-keeping.
      - name: RaBe Ansible
        label: rabe_ansible
        repositories:
          - name: Galaxy
            content_type: ansible_collection
            label: rabe_ansible_collections
            url: https://galaxy.ansible.com/
            ansible_collection_requirements: |-
              collections:
              - src: radiorabe.common
                name: radiorabe.common
              - src: radiorabe.foreman
                name: radiorabe.foreman
              - src: radiorabe.rabe_foreman
                name: radiorabe.rabe_foreman
      # We sync some extra repos like EPEL.
      - name: Extra Packages for Enterprise Linux 7
        label: epel7
        repositories:
          - name: Extra Packages for Enterprise Linux 7 x86_64
            content_type: yum
            label: epel7
            url: http://download.fedoraproject.org/pub/epel/7/x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: Extra Packages for Enterprise Linux 8
        label: epel8
        repositories:
          - name: Extra Packages for Enterprise Linux 8 Everything x86_64
            content_type: yum
            label: epel9_everything
            url: http://download.fedoraproject.org/pub/epel/8/Everything/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: Extra Packages for Enterprise Linux 8 Modular x86_64
            content_type: yum
            label: epel9_modular
            url: http://download.fedoraproject.org/pub/epel/8/Modular/x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: Extra Packages for Enterprise Linux 9
        label: epel9
        repositories:
          - name: Extra Packages for Enterprise Linux 9 x86_64
            content_type: yum
            label: epel9
            url: http://download.fedoraproject.org/pub/epel/9/Everything/x86_64/
            download_policy: on_demand
            auto_enabled: false
      # All of our distros should have access to foreman client tooling.
      - name: Foreman Client 3.4 EL7
        label: foremancliente34el7
        repositories:
          - name: Foreman Client 3.4 EL7 x86_64
            content_type: yum
            label: foreman34el7_client
            url: https://yum.theforeman.org/client/3.4/el7/x86_64/
            download_policy: on_demand
      - name: Foreman Client 3.4 EL8
        label: foremancliente34el8
        repositories:
          - name: Foreman Client 3.4 EL8 x86_64
            content_type: yum
            label: foreman34el8_client
            url: https://yum.theforeman.org/client/3.4/el8/x86_64/
            download_policy: on_demand
      - name: Foreman Client 3.4 EL9
        label: foremanclientel9
        repositories:
          - name: Foreman Client 3.4 EL9 x86_64
            content_type: yum
            label: foreman34el9_client
            url: https://yum.theforeman.org/client/3.4/el9/x86_64/
            download_policy: on_demand
      # old zabbix for exiting el7 machines
      - name: Zabbix 3.0 (LTS) EL7
        label: zabbix30el7
        repositories:
          - name: Zabbix 3.0 Official Repository - EL7 - x86_64
            content_type: yum
            label: zabbix30el7
            url: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/
            download_policy: on_demand
            auto_enabled: false
      # Modern(ish) Zabbix packages for all of our supported EL releases.
      - name: Zabbix 6.0 (LTS) EL7
        label: zabbix60el7
        repositories:
          - name: Zabbix 6.0 Official Repository - EL7 - x86_64
            content_type: yum
            label: zabbix60el7
            url: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: Zabbix 6.0 Official Repository (non-supported) - EL7 - x86_64
            content_type: yum
            label: zabbix60el7_unsupported
            url: https://repo.zabbix.com/non-supported/rhel/7/x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: Zabbix 6.0 (LTS) EL8
        label: zabbix60el8
        repositories:
          - name: Zabbix 6.0 Official Repository - EL8 - x86_64
            content_type: yum
            label: zabbix60el8
            url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: Zabbix 6.0 Official Repository (non-supported) - EL8 - x86_64
            content_type: yum
            label: zabbix60el8_unsupported
            url: https://repo.zabbix.com/non-supported/rhel/8/x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: Zabbix 6.0 (LTS) EL9
        label: zabbix60
        repositories:
          - name: Zabbix 6.0 Official Repository - EL9 - x86_64
            content_type: yum
            label: zabbix60
            url: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/
            download_policy: on_demand
            auto_enabled: false
          - name: Zabbix 6.0 Official Repository (non-supported) - EL9 - x86_64
            content_type: yum
            label: zabbix60_unsupported
            url: https://repo.zabbix.com/non-supported/rhel/9/x86_64/
            download_policy: on_demand
            auto_enabled: false
      # Some things we build and manage as part of a RaBe product. The aim
      # is to minimise these over time but some of them like rabe-zabbix
      # are widely used and not easy to replace.
      - name: RaBe Linux EL7
        label: rabeel7
        repositories:
          - name: Copr repo for rabe-zabbix x86_64
            content_type: yum
            label: rabeel7_rabezabbix
            url: https://download.copr.fedorainfracloud.org/results/hairmare/rabe-zabbix/rhel-7-x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: RaBe Linux EL8
        label: rabeel8
        repositories:
          - name: Copr repo for rabe-zabbix x86_64
            content_type: yum
            label: rabeel8_rabezabbix
            url: https://download.copr.fedorainfracloud.org/results/hairmare/rabe-zabbix/rhel-8-x86_64/
            download_policy: on_demand
            auto_enabled: false
      - name: RaBe Linux EL9
        label: rabeel9
        repositories:
          - name: Copr repo for rabe-zabbix x86_64
            content_type: yum
            label: rabeel9_rabezabbix
            url: https://download.copr.fedorainfracloud.org/results/hairmare/rabe-zabbix/rhel-9-x86_64/
            download_policy: on_demand
            auto_enabled: false
      # Some audio stuffs are needed as well
      - name: Paravel Systems EL7
        label: paravelel7
        repositories:
          - name: Broadcast Applications from Paravel Systems
            content_type: yum
            label: paravelel7_broadcast
            url: http://download.paravelsystems.com/CentOS/7/
            download_policy: on_demand
            auto_enabled: false
          - name: Commercial Applications from Paravel Systems
            content_type: yum
            label: paravelel7_commercial
            url: http://download.paravelsystems.com/CentOS/7com/
            download_policy: on_demand
            auto_enabled: false
