---
- name: 'RaBe Foreman Content : Configure Products'
  ansible.builtin.include_role:
    name: theforeman.foreman.repositories
  vars:
    foreman_products:
      - name: AlmaLinux 9
        label: alma9
        repositories:
          - name: AlmaLinux 9 BaseOS x86_64
            content_type: yum
            label: alma9_baseos
            url: https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 AppStream x86_64
            content_type: yum
            label: alma9_appstream
            url: https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 CRB x86_64
            content_type: yum
            label: alma9_crb
            url: https://repo.almalinux.org/almalinux/9/CRB/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 Extras x86_64
            content_type: yum
            label: alma9_extras
            url: https://repo.almalinux.org/almalinux/9/extras/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 HighAvailability x86_64
            content_type: yum
            label: alma9_ha
            url: https://repo.almalinux.org/almalinux/9/HighAvailability/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 NFV x86_64
            content_type: yum
            label: alma9_nfv
            url: https://repo.almalinux.org/almalinux/9/NFV/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 Plus x86_64
            content_type: yum
            label: alma9_plus
            url: https://repo.almalinux.org/almalinux/9/plus/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 ResilientStorage x86_64
            content_type: yum
            label: alma9_resilientstorage
            url: https://repo.almalinux.org/almalinux/9/ResilientStorage/x86_64/os/
            download_policy: on_demand
          - name: AlmaLinux 9 RT x86_64
            content_type: yum
            label: alma9_rt
            url: https://repo.almalinux.org/almalinux/9/RT/x86_64/os/
            download_policy: on_demand
      - name: CentOS 8 Stream
        label: cs8s
        repositories:
          - name: CentOS Stream 8 BaseOS x86_64
            content_type: yum
            label: cs8s_baseos
            url: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 AppStream x86_64
            content_type: yum
            label: cs8s_appstream
            url: http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 Extras x86_64
            content_type: yum
            label: cs8s_extras
            url: http://mirror.centos.org/centos/8-stream/extras/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 PowerTools x86_64
            content_type: yum
            label: cs8s_powertools
            url: http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 RealTime x86_64
            content_type: yum
            label: cs8s_rt
            url: http://mirror.centos.org/centos/8-stream/RT/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 HighAvailability x86_64
            content_type: yum
            label: cs8s_ha
            url: http://mirror.centos.org/centos/8-stream/HighAvailability/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 ResilientStorage x86_64
            content_type: yum
            label: cs8s_resilientstorage
            url: http://mirror.centos.org/centos/8-stream/ResilientStorage/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 NFV x86_64
            content_type: yum
            label: cs8s_nfv
            url: http://mirror.centos.org/centos/8-stream/NFV/x86_64/os/
            download_policy: on_demand
          - name: CentOS Stream 8 Foreman client 3.4 x86_64
            content_type: yum
            label: cs8s_foreman34_client
            url: https://yum.theforeman.org/client/3.4/el8/x86_64/
            download_policy: on_demand
      - name: CentOS 7
        label: c7
        repositories:
          - name: CentOS 7 OS x86_64
            content_type: yum
            label: c7_os
            url: http://mirror.centos.org/centos/7/os/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Extras x86_64
            content_type: yum
            label: c7_extras
            url: http://mirror.centos.org/centos/7/extras/x86_64/
            download_policy: on_demand
          - name: CentOS 7 FastTrack x86_64
            content_type: yum
            label: c7_fasttrack
            url: http://mirror.centos.org/centos/7/fasttrack/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Plus x86_64
            content_type: yum
            label: c7_plus
            url: http://mirror.centos.org/centos/7/centosplus/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Updates x86_64
            content_type: yum
            label: c7_updates
            url: http://mirror.centos.org/centos/7/updates/x86_64/
            download_policy: on_demand
          - name: CentOS 7 SCLo-rh x86_64
            content_type: yum
            label: c7_sclorh
            url: http://mirror.centos.org/centos/7/sclo/x86_64/rh/
            download_policy: on_demand
          - name: CentOS 7 SCLo-sclo x86_64
            content_type: yum
            label: c7_sclo
            url: http://mirror.centos.org/centos/7/sclo/x86_64/sclo/
            download_policy: on_demand
          - name: Extra Packages for Enterprise Linux 7 x86_64
            content_type: yum
            label: c7_epel
            url: http://download.fedoraproject.org/pub/epel/7/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Storage GlusterFS 3.7 x86_64
            content_type: yum
            label: c7_storage_glusterfs3
            url: https://download.gluster.org/pub/gluster/glusterfs/01.old-releases/3.7/LATEST/EPEL.repo/epel-7/x86_64/
            download_policy: on_demand
          - name: CentOS 7 Storage GlusterFS 10 x86_64
            content_type: yum
            label: c7_storage_glusterfs10
            url: http://mirror.centos.org/centos/7/storage/x86_64/gluster-10/
            download_policy: on_demand
      - name: Foreman
        label: theforeman
        repositories:
          - name: CentOS Configmanagement SIG - ansible-29
            label: centos-ansible-29
            content_type: yum
            download_policy: on_demand
            url: http://mirror.centos.org/centos/8/configmanagement/x86_64/ansible-29/
          - name: Ansible runner
            label: ansible-runner
            content_type: yum
            download_policy: on_demand
            url: https://releases.ansible.com/ansible-runner/rpm/epel-8-x86_64/
          - name: Foreman 3.3
            state: absent
            label: foreman33
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/releases/3.3/el8/x86_64/
          - name: Foreman plugins 3.3
            state: absent
            label: foreman33-plugins
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/plugins/3.3/el8/x86_64/
          - name: Foreman 3.4
            label: foreman34
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/releases/3.4/el8/x86_64/
          - name: Foreman plugins 3.4
            label: foreman34-plugins
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/plugins/3.4/el8/x86_64/
          - name: Katello 4.5
            state: absent
            label: katello45
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.5/katello/el8/x86_64/
          - name: Katello 4.6
            label: katello46
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.6/katello/el8/x86_64/
          - name: 'Candlepin: an open source entitlement management system.'
            label: katello45-candlepin
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/katello/4.5/candlepin/el8/x86_64/
          - name: 'pulpcore: Fetch, Upload, Organize, and Distribute Software Packages.'
            label: pulpcore
            content_type: yum
            download_policy: on_demand
            url: https://yum.theforeman.org/pulpcore/3.18/el8/x86_64/
          - name: Puppet 7 Repository el 8 - x86_64
            label: puppet7
            content_type: yum
            download_policy: on_demand
            url: http://yum.puppetlabs.com/puppet7/el/8/x86_64/
      - name: RaBe Ansible
        label: rabe_ansible
        repositories:
          - name: Galaxy
            content_type: ansible_collection
            label: rabe_ansible_collections
            url: https://galaxy.ansible.com/
            ansible_collection_requirements: |-
              collections:
              - src: radiorabe.common
                name: radiorabe.common
              - src: radiorabe.foreman
                name: radiorabe.foreman
              - src: radiorabe.rabe_foreman
                name: radiorabe.rabe_foreman
      - name: Foreman Client
        label: theforemanclient
        repositories:
          - name: EL8 Foreman Client 3.4 x86_64
            content_type: yum
            label: foreman34_client
            url: https://yum.theforeman.org/client/3.4/el8/x86_64/
            download_policy: on_demand
