---
description: AlmaLinux 9 virtual machines to be run on server-008
parent: RaBe Core/RaBe Base/EL9/AlmaLinux 9
organization: RaBe
location: Sulgenrain
domain: dmz.int.rabe.ch
subnet: dmz
compute_resource: server-008.dmz-admin.int.rabe.ch
compute_profile: "1-Small"
