---
- name: 'RaBe Foreman Hosts : Configure Installation Mediums'
  ansible.builtin.include_role:
    name: radiorabe.foreman.installation_mediums
  vars:
    foreman_installation_mediums:
      - name: CentOS 7 mirror
        state: absent
        os_family: Redhat
        path: http://mirror.centos.org/centos/$major/os/$arch
      - name: CentOS 8 mirror
        state: absent
        os_family: Redhat
        path: http://mirror.centos.org/centos/$major/BaseOS/$arch/kickstart
      - name: CentOS Stream
        state: present
        os_family: Redhat
        path: http://mirror.centos.org/centos/$major-stream/BaseOS/$arch/os
      - name: CoreOS mirror
        state: absent
        os_family: Coreos
        path: http://$release-temporary-archive.release.core-os.net
      - name: Debian mirror
        state: absent
        os_family: Debian
        path: http://ftp.debian.org/debian
      - name: Fedora Atomic mirror
        state: absent
        os_family: Redhat
        path: http://dl.fedoraproject.org/pub/alt/atomic/stable/Cloud_Atomic/$arch/os/
      - name: Fedora CoreOS mirror
        state: present
        os_family: Fcos
        path: https://builds.coreos.fedoraproject.org
      - name: Fedora mirror
        state: present
        os_family: Redhat
        path: http://dl.fedoraproject.org/pub/fedora/linux/releases/$major/Server/$arch/os/
      - name: Flatcar mirror
        state: absent
        os_family: Coreos
        path: http://$release.release.flatcar-linux.net
      - name: FreeBSD mirror
        state: absent
        os_family: Freebsd
        path: http://ftp.freebsd.org/pub/FreeBSD/releases/$arch/$version-RELEASE/
      - name: OpenSUSE mirror
        state: absent
        os_family: Suse
        path: http://download.opensuse.org/distribution/leap/$version/repo/oss
      - name: RancherOS mirror
        state: absent
        os_family: Rancheros
        path: https://github.com/rancher/os/releases/download/v$version
      - name: Red Hat CoreOS mirror
        state: absent
        os_family: Rhcos
        path: http://mirror.openshift.com
      - name: Ubuntu mirror
        state: absent
        os_family: Debian
        path: http://archive.ubuntu.com/ubuntu
      - name: AlmaLinux
        state: present
        os_family: Redhat
        path: https://repo.almalinux.org/almalinux/$major/BaseOS/$arch/os
