name: Release

on:
  release:
    types:
      - published

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/release-ansible-collection.yaml@v0.15.0
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
